// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\loginfo\index.qtpl:1
package loginfo

//line admin\views\loginfo\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line admin\views\loginfo\index.qtpl:2
import (
	"fasthttpweb/area"
	"fasthttpweb/area/commonhtmlhelper"
	"fasthttpweb/model"
)

//line admin\views\loginfo\index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\loginfo\index.qtpl:10
type IndexPage struct {
	*area.BasePage
}

//line admin\views\loginfo\index.qtpl:15
func (p *IndexPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\loginfo\index.qtpl:15
	p.BasePage.StreamRenderTitle(qw422016)
	//line admin\views\loginfo\index.qtpl:15
	qw422016.N().S(` `)
//line admin\views\loginfo\index.qtpl:15
}

//line admin\views\loginfo\index.qtpl:15
func (p *IndexPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\loginfo\index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\loginfo\index.qtpl:15
	p.StreamRenderTitle(qw422016)
	//line admin\views\loginfo\index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line admin\views\loginfo\index.qtpl:15
}

//line admin\views\loginfo\index.qtpl:15
func (p *IndexPage) RenderTitle() string {
	//line admin\views\loginfo\index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\loginfo\index.qtpl:15
	p.WriteRenderTitle(qb422016)
	//line admin\views\loginfo\index.qtpl:15
	qs422016 := string(qb422016.B)
	//line admin\views\loginfo\index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\loginfo\index.qtpl:15
	return qs422016
//line admin\views\loginfo\index.qtpl:15
}

//line admin\views\loginfo\index.qtpl:16
func (p *IndexPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\loginfo\index.qtpl:16
	p.BasePage.StreamRenderKwd(qw422016)
	//line admin\views\loginfo\index.qtpl:16
	qw422016.N().S(` `)
//line admin\views\loginfo\index.qtpl:16
}

//line admin\views\loginfo\index.qtpl:16
func (p *IndexPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\loginfo\index.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\loginfo\index.qtpl:16
	p.StreamRenderKwd(qw422016)
	//line admin\views\loginfo\index.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line admin\views\loginfo\index.qtpl:16
}

//line admin\views\loginfo\index.qtpl:16
func (p *IndexPage) RenderKwd() string {
	//line admin\views\loginfo\index.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\loginfo\index.qtpl:16
	p.WriteRenderKwd(qb422016)
	//line admin\views\loginfo\index.qtpl:16
	qs422016 := string(qb422016.B)
	//line admin\views\loginfo\index.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\loginfo\index.qtpl:16
	return qs422016
//line admin\views\loginfo\index.qtpl:16
}

//line admin\views\loginfo\index.qtpl:18
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\loginfo\index.qtpl:18
}

//line admin\views\loginfo\index.qtpl:18
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\loginfo\index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\loginfo\index.qtpl:18
	p.StreamRenderCss(qw422016)
	//line admin\views\loginfo\index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line admin\views\loginfo\index.qtpl:18
}

//line admin\views\loginfo\index.qtpl:18
func (p *IndexPage) RenderCss() string {
	//line admin\views\loginfo\index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\loginfo\index.qtpl:18
	p.WriteRenderCss(qb422016)
	//line admin\views\loginfo\index.qtpl:18
	qs422016 := string(qb422016.B)
	//line admin\views\loginfo\index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\loginfo\index.qtpl:18
	return qs422016
//line admin\views\loginfo\index.qtpl:18
}

//line admin\views\loginfo\index.qtpl:20
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line admin\views\loginfo\index.qtpl:20
}

//line admin\views\loginfo\index.qtpl:20
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\loginfo\index.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\loginfo\index.qtpl:20
	p.StreamRenderScript(qw422016)
	//line admin\views\loginfo\index.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line admin\views\loginfo\index.qtpl:20
}

//line admin\views\loginfo\index.qtpl:20
func (p *IndexPage) RenderScript() string {
	//line admin\views\loginfo\index.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\loginfo\index.qtpl:20
	p.WriteRenderScript(qb422016)
	//line admin\views\loginfo\index.qtpl:20
	qs422016 := string(qb422016.B)
	//line admin\views\loginfo\index.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\loginfo\index.qtpl:20
	return qs422016
//line admin\views\loginfo\index.qtpl:20
}

//line admin\views\loginfo\index.qtpl:22
func (p *IndexPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\loginfo\index.qtpl:22
	qw422016.N().S(`
	`)
	//line admin\views\loginfo\index.qtpl:24
	modelVal := p.BasePage.BPD.Data["Model"]
	pageIndex := p.BPD.Data["page"].(int)
	total := p.BasePage.BPD.Data["Total"].(int)
	var loginfoes []model.LogInfo
	if modelVal != nil {
		loginfoes = modelVal.([]model.LogInfo)
	}

	//line admin\views\loginfo\index.qtpl:31
	qw422016.N().S(`
	
	<div class="text-center">
		`)
	//line admin\views\loginfo\index.qtpl:34
	if loginfoes != nil {
		//line admin\views\loginfo\index.qtpl:34
		qw422016.N().S(`
			<table class="table table-borderd table-hover">
			`)
		//line admin\views\loginfo\index.qtpl:36
		for _, v := range loginfoes {
			//line admin\views\loginfo\index.qtpl:36
			qw422016.N().S(`
			`)
			//line admin\views\loginfo\index.qtpl:38
			id := int(v.ID)
			data := make(map[string]interface{})
			data["id"] = id

			//line admin\views\loginfo\index.qtpl:41
			qw422016.N().S(`
				<tr>
					<td><a href="`)
			//line admin\views\loginfo\index.qtpl:43
			qw422016.E().S(area.Url(p.BasePage, "detail", data))
			//line admin\views\loginfo\index.qtpl:43
			qw422016.N().S(`">`)
			//line admin\views\loginfo\index.qtpl:43
			qw422016.E().S(v.IP)
			//line admin\views\loginfo\index.qtpl:43
			qw422016.N().S(`</a></td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:44
			qw422016.E().S(v.UserAgent)
			//line admin\views\loginfo\index.qtpl:44
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:45
			qw422016.E().S(v.ExpMsg)
			//line admin\views\loginfo\index.qtpl:45
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:46
			qw422016.E().S(v.LoggerLevel)
			//line admin\views\loginfo\index.qtpl:46
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:47
			qw422016.E().S(v.LogCatelog)
			//line admin\views\loginfo\index.qtpl:47
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:48
			qw422016.E().S(v.Msg)
			//line admin\views\loginfo\index.qtpl:48
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:49
			qw422016.E().S(v.Url)
			//line admin\views\loginfo\index.qtpl:49
			qw422016.N().S(`</td>
					<td>`)
			//line admin\views\loginfo\index.qtpl:50
			qw422016.E().S(v.CreateTime.Format("2006-01-02 15:04:05"))
			//line admin\views\loginfo\index.qtpl:50
			qw422016.N().S(`</td>
					<td>
						<a href="`)
			//line admin\views\loginfo\index.qtpl:52
			qw422016.E().S(area.Url(p.BasePage, "edit", data))
			//line admin\views\loginfo\index.qtpl:52
			qw422016.N().S(`">编辑</a>
						<a href="`)
			//line admin\views\loginfo\index.qtpl:53
			qw422016.E().S(area.Url(p.BasePage, "mdelete", data))
			//line admin\views\loginfo\index.qtpl:53
			qw422016.N().S(`">删除</a>
					</td>
				</tr>
			`)
			//line admin\views\loginfo\index.qtpl:56
		}
		//line admin\views\loginfo\index.qtpl:56
		qw422016.N().S(`
			</table>
			`)
		//line admin\views\loginfo\index.qtpl:58
		qw422016.N().S(commonhtmlhelper.GeneratePageLink("", pageIndex, 5, total, "page", nil))
		//line admin\views\loginfo\index.qtpl:58
		qw422016.N().S(`
		`)
		//line admin\views\loginfo\index.qtpl:59
	}
	//line admin\views\loginfo\index.qtpl:59
	qw422016.N().S(`
	</div>
`)
//line admin\views\loginfo\index.qtpl:61
}

//line admin\views\loginfo\index.qtpl:61
func (p *IndexPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\loginfo\index.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\loginfo\index.qtpl:61
	p.StreamRenderBody(qw422016)
	//line admin\views\loginfo\index.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line admin\views\loginfo\index.qtpl:61
}

//line admin\views\loginfo\index.qtpl:61
func (p *IndexPage) RenderBody() string {
	//line admin\views\loginfo\index.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\loginfo\index.qtpl:61
	p.WriteRenderBody(qb422016)
	//line admin\views\loginfo\index.qtpl:61
	qs422016 := string(qb422016.B)
	//line admin\views\loginfo\index.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\loginfo\index.qtpl:61
	return qs422016
//line admin\views\loginfo\index.qtpl:61
}
