// This file is automatically generated by qtc from "detail.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\user\detail.qtpl:1
package user

//line admin\views\user\detail.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line admin\views\user\detail.qtpl:2
import (
	"fasthttpweb/area"
	"fasthttpweb/model"
)

//line admin\views\user\detail.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\user\detail.qtpl:9
type DetailPage struct {
	*area.BasePage
}

//line admin\views\user\detail.qtpl:14
func (p *DetailPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\user\detail.qtpl:14
	p.BasePage.StreamRenderTitle(qw422016)
	//line admin\views\user\detail.qtpl:14
	qw422016.N().S(` `)
//line admin\views\user\detail.qtpl:14
}

//line admin\views\user\detail.qtpl:14
func (p *DetailPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\user\detail.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\user\detail.qtpl:14
	p.StreamRenderTitle(qw422016)
	//line admin\views\user\detail.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line admin\views\user\detail.qtpl:14
}

//line admin\views\user\detail.qtpl:14
func (p *DetailPage) RenderTitle() string {
	//line admin\views\user\detail.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\user\detail.qtpl:14
	p.WriteRenderTitle(qb422016)
	//line admin\views\user\detail.qtpl:14
	qs422016 := string(qb422016.B)
	//line admin\views\user\detail.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\user\detail.qtpl:14
	return qs422016
//line admin\views\user\detail.qtpl:14
}

//line admin\views\user\detail.qtpl:15
func (p *DetailPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\user\detail.qtpl:15
	p.BasePage.StreamRenderKwd(qw422016)
	//line admin\views\user\detail.qtpl:15
	qw422016.N().S(` `)
//line admin\views\user\detail.qtpl:15
}

//line admin\views\user\detail.qtpl:15
func (p *DetailPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\user\detail.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\user\detail.qtpl:15
	p.StreamRenderKwd(qw422016)
	//line admin\views\user\detail.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line admin\views\user\detail.qtpl:15
}

//line admin\views\user\detail.qtpl:15
func (p *DetailPage) RenderKwd() string {
	//line admin\views\user\detail.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\user\detail.qtpl:15
	p.WriteRenderKwd(qb422016)
	//line admin\views\user\detail.qtpl:15
	qs422016 := string(qb422016.B)
	//line admin\views\user\detail.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\user\detail.qtpl:15
	return qs422016
//line admin\views\user\detail.qtpl:15
}

//line admin\views\user\detail.qtpl:17
func (p *DetailPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\user\detail.qtpl:17
}

//line admin\views\user\detail.qtpl:17
func (p *DetailPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\user\detail.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\user\detail.qtpl:17
	p.StreamRenderCss(qw422016)
	//line admin\views\user\detail.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line admin\views\user\detail.qtpl:17
}

//line admin\views\user\detail.qtpl:17
func (p *DetailPage) RenderCss() string {
	//line admin\views\user\detail.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\user\detail.qtpl:17
	p.WriteRenderCss(qb422016)
	//line admin\views\user\detail.qtpl:17
	qs422016 := string(qb422016.B)
	//line admin\views\user\detail.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\user\detail.qtpl:17
	return qs422016
//line admin\views\user\detail.qtpl:17
}

//line admin\views\user\detail.qtpl:19
func (p *DetailPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line admin\views\user\detail.qtpl:19
}

//line admin\views\user\detail.qtpl:19
func (p *DetailPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\user\detail.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\user\detail.qtpl:19
	p.StreamRenderScript(qw422016)
	//line admin\views\user\detail.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line admin\views\user\detail.qtpl:19
}

//line admin\views\user\detail.qtpl:19
func (p *DetailPage) RenderScript() string {
	//line admin\views\user\detail.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\user\detail.qtpl:19
	p.WriteRenderScript(qb422016)
	//line admin\views\user\detail.qtpl:19
	qs422016 := string(qb422016.B)
	//line admin\views\user\detail.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\user\detail.qtpl:19
	return qs422016
//line admin\views\user\detail.qtpl:19
}

//line admin\views\user\detail.qtpl:21
func (p *DetailPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\user\detail.qtpl:21
	qw422016.N().S(`
	`)
	//line admin\views\user\detail.qtpl:23
	modelVal := p.BasePage.BPD.Data["Model"]
	var user *model.Users
	if modelVal != nil {
		user = modelVal.(*model.Users)
	}

	//line admin\views\user\detail.qtpl:28
	qw422016.N().S(`
	<div class="text-center">
		`)
	//line admin\views\user\detail.qtpl:30
	if user != nil {
		//line admin\views\user\detail.qtpl:30
		qw422016.N().S(`
			<div>`)
		//line admin\views\user\detail.qtpl:31
		qw422016.E().S(user.Name)
		//line admin\views\user\detail.qtpl:31
		qw422016.N().S(`</div>
			<div>`)
		//line admin\views\user\detail.qtpl:32
		qw422016.E().S(user.CreateTime.Format("2006-01-02 15:04:05"))
		//line admin\views\user\detail.qtpl:32
		qw422016.N().S(`</div>
			<div>`)
		//line admin\views\user\detail.qtpl:33
		if user.Used {
			//line admin\views\user\detail.qtpl:33
			qw422016.N().S(`是`)
			//line admin\views\user\detail.qtpl:33
		} else {
			//line admin\views\user\detail.qtpl:33
			qw422016.N().S(`否`)
			//line admin\views\user\detail.qtpl:33
		}
		//line admin\views\user\detail.qtpl:33
		qw422016.N().S(`</div>
		`)
		//line admin\views\user\detail.qtpl:34
	}
	//line admin\views\user\detail.qtpl:34
	qw422016.N().S(`
	</div>
`)
//line admin\views\user\detail.qtpl:36
}

//line admin\views\user\detail.qtpl:36
func (p *DetailPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\user\detail.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\user\detail.qtpl:36
	p.StreamRenderBody(qw422016)
	//line admin\views\user\detail.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line admin\views\user\detail.qtpl:36
}

//line admin\views\user\detail.qtpl:36
func (p *DetailPage) RenderBody() string {
	//line admin\views\user\detail.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\user\detail.qtpl:36
	p.WriteRenderBody(qb422016)
	//line admin\views\user\detail.qtpl:36
	qs422016 := string(qb422016.B)
	//line admin\views\user\detail.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\user\detail.qtpl:36
	return qs422016
//line admin\views\user\detail.qtpl:36
}
