// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\index.qtpl:1
package views

//line admin\views\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line admin\views\index.qtpl:4
import (
	"github.com/valyala/fasthttp"
)

//line admin\views\index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\index.qtpl:10
type IndexPage struct {
	CTX    *fasthttp.RequestCtx
	Titles string
}

//line admin\views\index.qtpl:17
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line admin\views\index.qtpl:17
	qw422016.N().S(`
	`)
	//line admin\views\index.qtpl:18
	qw422016.E().S(p.Titles)
	//line admin\views\index.qtpl:18
	qw422016.N().S(`
`)
//line admin\views\index.qtpl:19
}

//line admin\views\index.qtpl:19
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line admin\views\index.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\index.qtpl:19
	p.StreamTitle(qw422016)
	//line admin\views\index.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line admin\views\index.qtpl:19
}

//line admin\views\index.qtpl:19
func (p *IndexPage) Title() string {
	//line admin\views\index.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\index.qtpl:19
	p.WriteTitle(qb422016)
	//line admin\views\index.qtpl:19
	qs422016 := string(qb422016.B)
	//line admin\views\index.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\index.qtpl:19
	return qs422016
//line admin\views\index.qtpl:19
}

//line admin\views\index.qtpl:21
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
	//line admin\views\index.qtpl:21
	qw422016.N().S(`
`)
//line admin\views\index.qtpl:22
}

//line admin\views\index.qtpl:22
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\index.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\index.qtpl:22
	p.StreamRenderCss(qw422016)
	//line admin\views\index.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line admin\views\index.qtpl:22
}

//line admin\views\index.qtpl:22
func (p *IndexPage) RenderCss() string {
	//line admin\views\index.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\index.qtpl:22
	p.WriteRenderCss(qb422016)
	//line admin\views\index.qtpl:22
	qs422016 := string(qb422016.B)
	//line admin\views\index.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\index.qtpl:22
	return qs422016
//line admin\views\index.qtpl:22
}

//line admin\views\index.qtpl:24
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
	//line admin\views\index.qtpl:24
	qw422016.N().S(`
`)
//line admin\views\index.qtpl:25
}

//line admin\views\index.qtpl:25
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\index.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\index.qtpl:25
	p.StreamRenderScript(qw422016)
	//line admin\views\index.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line admin\views\index.qtpl:25
}

//line admin\views\index.qtpl:25
func (p *IndexPage) RenderScript() string {
	//line admin\views\index.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\index.qtpl:25
	p.WriteRenderScript(qb422016)
	//line admin\views\index.qtpl:25
	qs422016 := string(qb422016.B)
	//line admin\views\index.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\index.qtpl:25
	return qs422016
//line admin\views\index.qtpl:25
}

//line admin\views\index.qtpl:27
func (p *IndexPage) StreamKwd(qw422016 *qt422016.Writer) {
	//line admin\views\index.qtpl:27
	qw422016.N().S(`
	kwds,kwds1,kwds2,kwds3
`)
//line admin\views\index.qtpl:29
}

//line admin\views\index.qtpl:29
func (p *IndexPage) WriteKwd(qq422016 qtio422016.Writer) {
	//line admin\views\index.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\index.qtpl:29
	p.StreamKwd(qw422016)
	//line admin\views\index.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line admin\views\index.qtpl:29
}

//line admin\views\index.qtpl:29
func (p *IndexPage) Kwd() string {
	//line admin\views\index.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\index.qtpl:29
	p.WriteKwd(qb422016)
	//line admin\views\index.qtpl:29
	qs422016 := string(qb422016.B)
	//line admin\views\index.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\index.qtpl:29
	return qs422016
//line admin\views\index.qtpl:29
}

//line admin\views\index.qtpl:31
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line admin\views\index.qtpl:31
	qw422016.N().S(`
	<div class="text-center">
		admin- success
	</div>
`)
//line admin\views\index.qtpl:35
}

//line admin\views\index.qtpl:35
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line admin\views\index.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\index.qtpl:35
	p.StreamBody(qw422016)
	//line admin\views\index.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line admin\views\index.qtpl:35
}

//line admin\views\index.qtpl:35
func (p *IndexPage) Body() string {
	//line admin\views\index.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\index.qtpl:35
	p.WriteBody(qb422016)
	//line admin\views\index.qtpl:35
	qs422016 := string(qb422016.B)
	//line admin\views\index.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\index.qtpl:35
	return qs422016
//line admin\views\index.qtpl:35
}
