// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\index.qtpl:1
package index

//line home\views\index\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line home\views\index\index.qtpl:3
import (
	"fasthttpweb/area"
	"fasthttpweb/model"
)

//line home\views\index\index.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\index.qtpl:9
type IndexPage struct {
	*area.BasePage
}

//line home\views\index\index.qtpl:14
func (p *IndexPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:14
p.StreamRender_Title(qw422016) }

//line home\views\index\index.qtpl:14
//line home\views\index\index.qtpl:14
func (p *IndexPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:14
	p.StreamRenderTitle(qw422016)
	//line home\views\index\index.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:14
}

//line home\views\index\index.qtpl:14
func (p *IndexPage) RenderTitle() string {
	//line home\views\index\index.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:14
	p.WriteRenderTitle(qb422016)
	//line home\views\index\index.qtpl:14
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:14
	return qs422016
//line home\views\index\index.qtpl:14
}

//line home\views\index\index.qtpl:15
func (p *IndexPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\index.qtpl:15
	qw422016.N().S(` `)
	//line home\views\index\index.qtpl:15
	p.StreamRender_Kwd(qw422016)
//line home\views\index\index.qtpl:15
}

//line home\views\index\index.qtpl:15
func (p *IndexPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:15
	p.StreamRenderKwd(qw422016)
	//line home\views\index\index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:15
}

//line home\views\index\index.qtpl:15
func (p *IndexPage) RenderKwd() string {
	//line home\views\index\index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:15
	p.WriteRenderKwd(qb422016)
	//line home\views\index\index.qtpl:15
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:15
	return qs422016
//line home\views\index\index.qtpl:15
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:17
	p.StreamRenderCss(qw422016)
	//line home\views\index\index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) RenderCss() string {
	//line home\views\index\index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:17
	p.WriteRenderCss(qb422016)
	//line home\views\index\index.qtpl:17
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:17
	return qs422016
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:18
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:18
}

//line home\views\index\index.qtpl:18
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:18
	p.StreamRenderScript(qw422016)
	//line home\views\index\index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:18
}

//line home\views\index\index.qtpl:18
func (p *IndexPage) RenderScript() string {
	//line home\views\index\index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:18
	p.WriteRenderScript(qb422016)
	//line home\views\index\index.qtpl:18
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:18
	return qs422016
//line home\views\index\index.qtpl:18
}

//line home\views\index\index.qtpl:20
func (p *IndexPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\index.qtpl:20
	qw422016.N().S(`
	<div class="text-center">
		success
		`)
	//line home\views\index\index.qtpl:23
	qw422016.E().S(p.BPD.Data["user"].(*model.Users).Name)
	//line home\views\index\index.qtpl:23
	qw422016.N().S(`
	</div>
`)
//line home\views\index\index.qtpl:25
}

//line home\views\index\index.qtpl:25
func (p *IndexPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:25
	p.StreamRenderBody(qw422016)
	//line home\views\index\index.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:25
}

//line home\views\index\index.qtpl:25
func (p *IndexPage) RenderBody() string {
	//line home\views\index\index.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:25
	p.WriteRenderBody(qb422016)
	//line home\views\index\index.qtpl:25
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:25
	return qs422016
//line home\views\index\index.qtpl:25
}
