// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\index.qtpl:1
package index

//line home\views\index\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line home\views\index\index.qtpl:3
import (
	"fasthttpweb/area"
)

//line home\views\index\index.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\index.qtpl:8
type IndexPage struct {
	*area.BasePage
}

//line home\views\index\index.qtpl:13
func (p *IndexPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:13
p.StreamRender_Title(qw422016) }

//line home\views\index\index.qtpl:13
//line home\views\index\index.qtpl:13
func (p *IndexPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:13
	p.StreamRenderTitle(qw422016)
	//line home\views\index\index.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:13
}

//line home\views\index\index.qtpl:13
func (p *IndexPage) RenderTitle() string {
	//line home\views\index\index.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:13
	p.WriteRenderTitle(qb422016)
	//line home\views\index\index.qtpl:13
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:13
	return qs422016
//line home\views\index\index.qtpl:13
}

//line home\views\index\index.qtpl:14
func (p *IndexPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\index.qtpl:14
	qw422016.N().S(` `)
	//line home\views\index\index.qtpl:14
	p.StreamRender_Kwd(qw422016)
//line home\views\index\index.qtpl:14
}

//line home\views\index\index.qtpl:14
func (p *IndexPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:14
	p.StreamRenderKwd(qw422016)
	//line home\views\index\index.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:14
}

//line home\views\index\index.qtpl:14
func (p *IndexPage) RenderKwd() string {
	//line home\views\index\index.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:14
	p.WriteRenderKwd(qb422016)
	//line home\views\index\index.qtpl:14
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:14
	return qs422016
//line home\views\index\index.qtpl:14
}

//line home\views\index\index.qtpl:16
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:16
}

//line home\views\index\index.qtpl:16
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:16
	p.StreamRenderCss(qw422016)
	//line home\views\index\index.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:16
}

//line home\views\index\index.qtpl:16
func (p *IndexPage) RenderCss() string {
	//line home\views\index\index.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:16
	p.WriteRenderCss(qb422016)
	//line home\views\index\index.qtpl:16
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:16
	return qs422016
//line home\views\index\index.qtpl:16
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:17
	p.StreamRenderScript(qw422016)
	//line home\views\index\index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:17
func (p *IndexPage) RenderScript() string {
	//line home\views\index\index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:17
	p.WriteRenderScript(qb422016)
	//line home\views\index\index.qtpl:17
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:17
	return qs422016
//line home\views\index\index.qtpl:17
}

//line home\views\index\index.qtpl:19
func (p *IndexPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\index.qtpl:19
	qw422016.N().S(`
	<div class="text-center">
		<a href="/admin/user/logout">退出</a>
	</div>
`)
//line home\views\index\index.qtpl:23
}

//line home\views\index\index.qtpl:23
func (p *IndexPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\index.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\index.qtpl:23
	p.StreamRenderBody(qw422016)
	//line home\views\index\index.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\index.qtpl:23
}

//line home\views\index\index.qtpl:23
func (p *IndexPage) RenderBody() string {
	//line home\views\index\index.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\index.qtpl:23
	p.WriteRenderBody(qb422016)
	//line home\views\index\index.qtpl:23
	qs422016 := string(qb422016.B)
	//line home\views\index\index.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\index.qtpl:23
	return qs422016
//line home\views\index\index.qtpl:23
}
