// This file is automatically generated by qtc from "pagetest.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\pagetest.qtpl:1
package index

//line home\views\index\pagetest.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line home\views\index\pagetest.qtpl:1
import (
	"fasthttpweb/area"
	"fasthttpweb/area/commonhtmlhelper"
)

//line home\views\index\pagetest.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\pagetest.qtpl:7
type PageTest struct {
	*area.BasePage
}

//line home\views\index\pagetest.qtpl:12
func (p *PageTest) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line home\views\index\pagetest.qtpl:12
	p.BasePage.StreamRenderTitle(qw422016)
//line home\views\index\pagetest.qtpl:12
}

//line home\views\index\pagetest.qtpl:12
func (p *PageTest) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\pagetest.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\pagetest.qtpl:12
	p.StreamRenderTitle(qw422016)
	//line home\views\index\pagetest.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\pagetest.qtpl:12
}

//line home\views\index\pagetest.qtpl:12
func (p *PageTest) RenderTitle() string {
	//line home\views\index\pagetest.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\pagetest.qtpl:12
	p.WriteRenderTitle(qb422016)
	//line home\views\index\pagetest.qtpl:12
	qs422016 := string(qb422016.B)
	//line home\views\index\pagetest.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\pagetest.qtpl:12
	return qs422016
//line home\views\index\pagetest.qtpl:12
}

//line home\views\index\pagetest.qtpl:13
func (p *PageTest) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\pagetest.qtpl:13
	qw422016.N().S(` `)
	//line home\views\index\pagetest.qtpl:13
	p.BasePage.StreamRenderKwd(qw422016)
//line home\views\index\pagetest.qtpl:13
}

//line home\views\index\pagetest.qtpl:13
func (p *PageTest) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\pagetest.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\pagetest.qtpl:13
	p.StreamRenderKwd(qw422016)
	//line home\views\index\pagetest.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\pagetest.qtpl:13
}

//line home\views\index\pagetest.qtpl:13
func (p *PageTest) RenderKwd() string {
	//line home\views\index\pagetest.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\pagetest.qtpl:13
	p.WriteRenderKwd(qb422016)
	//line home\views\index\pagetest.qtpl:13
	qs422016 := string(qb422016.B)
	//line home\views\index\pagetest.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\pagetest.qtpl:13
	return qs422016
//line home\views\index\pagetest.qtpl:13
}

//line home\views\index\pagetest.qtpl:15
func (p *PageTest) StreamRenderCss(qw422016 *qt422016.Writer) {
//line home\views\index\pagetest.qtpl:15
}

//line home\views\index\pagetest.qtpl:15
func (p *PageTest) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\pagetest.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\pagetest.qtpl:15
	p.StreamRenderCss(qw422016)
	//line home\views\index\pagetest.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\pagetest.qtpl:15
}

//line home\views\index\pagetest.qtpl:15
func (p *PageTest) RenderCss() string {
	//line home\views\index\pagetest.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\pagetest.qtpl:15
	p.WriteRenderCss(qb422016)
	//line home\views\index\pagetest.qtpl:15
	qs422016 := string(qb422016.B)
	//line home\views\index\pagetest.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\pagetest.qtpl:15
	return qs422016
//line home\views\index\pagetest.qtpl:15
}

//line home\views\index\pagetest.qtpl:16
func (p *PageTest) StreamRenderScript(qw422016 *qt422016.Writer) {
//line home\views\index\pagetest.qtpl:16
}

//line home\views\index\pagetest.qtpl:16
func (p *PageTest) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\pagetest.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\pagetest.qtpl:16
	p.StreamRenderScript(qw422016)
	//line home\views\index\pagetest.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\pagetest.qtpl:16
}

//line home\views\index\pagetest.qtpl:16
func (p *PageTest) RenderScript() string {
	//line home\views\index\pagetest.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\pagetest.qtpl:16
	p.WriteRenderScript(qb422016)
	//line home\views\index\pagetest.qtpl:16
	qs422016 := string(qb422016.B)
	//line home\views\index\pagetest.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\pagetest.qtpl:16
	return qs422016
//line home\views\index\pagetest.qtpl:16
}

//line home\views\index\pagetest.qtpl:18
func (p *PageTest) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\pagetest.qtpl:18
	qw422016.N().S(`
	<div class="text-center">
	`)
	//line home\views\index\pagetest.qtpl:21
	pageIndex := p.BPD.Data["page"].(int)
	data := make(map[string]interface{})
	data["abc"] = "abc"
	data["sh"] = 123

	//line home\views\index\pagetest.qtpl:25
	qw422016.N().S(`
		`)
	//line home\views\index\pagetest.qtpl:26
	qw422016.N().S(commonhtmlhelper.GeneratePageLink("", pageIndex, 5, 100, "page", data))
	//line home\views\index\pagetest.qtpl:26
	qw422016.N().S(`
	</div>
`)
//line home\views\index\pagetest.qtpl:28
}

//line home\views\index\pagetest.qtpl:28
func (p *PageTest) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\pagetest.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\pagetest.qtpl:28
	p.StreamRenderBody(qw422016)
	//line home\views\index\pagetest.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\pagetest.qtpl:28
}

//line home\views\index\pagetest.qtpl:28
func (p *PageTest) RenderBody() string {
	//line home\views\index\pagetest.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\pagetest.qtpl:28
	p.WriteRenderBody(qb422016)
	//line home\views\index\pagetest.qtpl:28
	qs422016 := string(qb422016.B)
	//line home\views\index\pagetest.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\pagetest.qtpl:28
	return qs422016
//line home\views\index\pagetest.qtpl:28
}
