// This file is automatically generated by qtc from "verify.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\verify.qtpl:1
package index

//line home\views\index\verify.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Implements BasePage methods.
//

//line home\views\index\verify.qtpl:3
import (
	"fasthttpweb/area"
	"github.com/valyala/fasthttp"
)

//line home\views\index\verify.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\verify.qtpl:9
type VerfyPage struct {
	CTX      *fasthttp.RequestCtx
	BPD      *area.BasePageData
	Titles   string
	ErrorMsg string
}

//line home\views\index\verify.qtpl:17
func (p *VerfyPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:17
	if p.BPD.Data != nil && p.BPD.Data["Title"] != nil {
		//line home\views\index\verify.qtpl:17
		qw422016.E().S(p.BPD.Data["Title"].(string))
		//line home\views\index\verify.qtpl:17
	}
//line home\views\index\verify.qtpl:17
}

//line home\views\index\verify.qtpl:17
func (p *VerfyPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:17
	p.StreamTitle(qw422016)
	//line home\views\index\verify.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:17
}

//line home\views\index\verify.qtpl:17
func (p *VerfyPage) Title() string {
	//line home\views\index\verify.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:17
	p.WriteTitle(qb422016)
	//line home\views\index\verify.qtpl:17
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:17
	return qs422016
//line home\views\index\verify.qtpl:17
}

//line home\views\index\verify.qtpl:19
func (p *VerfyPage) StreamRenderCss(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:19
	qw422016.N().S(`
	<style type="text/css">
		#vcode{
			cursor:pointer;
		}
	</style>
`)
//line home\views\index\verify.qtpl:25
}

//line home\views\index\verify.qtpl:25
func (p *VerfyPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:25
	p.StreamRenderCss(qw422016)
	//line home\views\index\verify.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:25
}

//line home\views\index\verify.qtpl:25
func (p *VerfyPage) RenderCss() string {
	//line home\views\index\verify.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:25
	p.WriteRenderCss(qb422016)
	//line home\views\index\verify.qtpl:25
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:25
	return qs422016
//line home\views\index\verify.qtpl:25
}

//line home\views\index\verify.qtpl:27
func (p *VerfyPage) StreamRenderScript(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:27
	qw422016.N().S(`
<script type="text/javascript">
	$(function(){
		$('#vcode').click(function(){
			$(this).prop('src','/api/verifyimg?r='+Math.random());
		});
		$(':submit').click(function(){
			var phone=$('#phone').val(),vcode=$('#vc').val();
			if(!(phone.length>0 && vcode.length>0)){
				$('.text-danger').text('手机号或验证码不能为空!');
				return false;
			}
		});
	})
</script>
`)
//line home\views\index\verify.qtpl:42
}

//line home\views\index\verify.qtpl:42
func (p *VerfyPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:42
	p.StreamRenderScript(qw422016)
	//line home\views\index\verify.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:42
}

//line home\views\index\verify.qtpl:42
func (p *VerfyPage) RenderScript() string {
	//line home\views\index\verify.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:42
	p.WriteRenderScript(qb422016)
	//line home\views\index\verify.qtpl:42
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:42
	return qs422016
//line home\views\index\verify.qtpl:42
}

//line home\views\index\verify.qtpl:44
func (p *VerfyPage) StreamKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:44
	qw422016.N().S(`
	kwds,kwds1,kwds2,kwds3
`)
//line home\views\index\verify.qtpl:46
}

//line home\views\index\verify.qtpl:46
func (p *VerfyPage) WriteKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:46
	p.StreamKwd(qw422016)
	//line home\views\index\verify.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:46
}

//line home\views\index\verify.qtpl:46
func (p *VerfyPage) Kwd() string {
	//line home\views\index\verify.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:46
	p.WriteKwd(qb422016)
	//line home\views\index\verify.qtpl:46
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:46
	return qs422016
//line home\views\index\verify.qtpl:46
}

//line home\views\index\verify.qtpl:48
func (p *VerfyPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:48
	qw422016.N().S(`
<div class="text-danger">`)
	//line home\views\index\verify.qtpl:49
	qw422016.E().S(p.ErrorMsg)
	//line home\views\index\verify.qtpl:49
	qw422016.N().S(`</div>
	<div class="text-center">
		<form action="/home/index/verify" method="POST">
			手机号:<input type="phone" id="phone" name="phone" /><br />
			验证码:<input type="text" id="vc" name="vcode" /><img id="vcode" src="/api/verifyimg" title="点击切换验证码" />
			<button type="submit" class="btn btn-default">去逛逛</button>
		</form>
	</div>
`)
//line home\views\index\verify.qtpl:57
}

//line home\views\index\verify.qtpl:57
func (p *VerfyPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:57
	p.StreamRenderBody(qw422016)
	//line home\views\index\verify.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:57
}

//line home\views\index\verify.qtpl:57
func (p *VerfyPage) RenderBody() string {
	//line home\views\index\verify.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:57
	p.WriteRenderBody(qb422016)
	//line home\views\index\verify.qtpl:57
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:57
	return qs422016
//line home\views\index\verify.qtpl:57
}
