// This file is automatically generated by qtc from "verify.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\verify.qtpl:1
package index

//line home\views\index\verify.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line home\views\index\verify.qtpl:1
import (
	"fasthttpweb/area"
	"fasthttpweb/area/commonhtmlhelper"
)

//line home\views\index\verify.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\verify.qtpl:7
type VerfyPage struct {
	*area.BasePage
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:12
	p.BasePage.StreamRenderTitle(qw422016)
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:12
	p.StreamRenderTitle(qw422016)
	//line home\views\index\verify.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) RenderTitle() string {
	//line home\views\index\verify.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:12
	p.WriteRenderTitle(qb422016)
	//line home\views\index\verify.qtpl:12
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:12
	return qs422016
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:13
func (p *VerfyPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:13
	qw422016.N().S(` `)
	//line home\views\index\verify.qtpl:13
	p.BasePage.StreamRenderKwd(qw422016)
	//line home\views\index\verify.qtpl:13
	qw422016.N().S(` `)
//line home\views\index\verify.qtpl:13
}

//line home\views\index\verify.qtpl:13
func (p *VerfyPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:13
	p.StreamRenderKwd(qw422016)
	//line home\views\index\verify.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:13
}

//line home\views\index\verify.qtpl:13
func (p *VerfyPage) RenderKwd() string {
	//line home\views\index\verify.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:13
	p.WriteRenderKwd(qb422016)
	//line home\views\index\verify.qtpl:13
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:13
	return qs422016
//line home\views\index\verify.qtpl:13
}

//line home\views\index\verify.qtpl:15
func (p *VerfyPage) StreamRenderCss(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:15
	qw422016.N().S(`
	<style type="text/css">
		#vcode{
			cursor:pointer;
		}
	</style>
`)
//line home\views\index\verify.qtpl:21
}

//line home\views\index\verify.qtpl:21
func (p *VerfyPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:21
	p.StreamRenderCss(qw422016)
	//line home\views\index\verify.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:21
}

//line home\views\index\verify.qtpl:21
func (p *VerfyPage) RenderCss() string {
	//line home\views\index\verify.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:21
	p.WriteRenderCss(qb422016)
	//line home\views\index\verify.qtpl:21
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:21
	return qs422016
//line home\views\index\verify.qtpl:21
}

//line home\views\index\verify.qtpl:23
func (p *VerfyPage) StreamRenderScript(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:23
	qw422016.N().S(`
<script type="text/javascript">
	$(function(){
		$('#vcode').click(function(){
			var url=$(this).prop('src');
			$(this).prop('src',url.split('&')[0]+'&r='+Math.random());
		});
		$(':submit').click(function(){
			var phone=$('#phone').val(),vcode=$('#vc').val();
			if(!(phone.length>0 && vcode.length>0)){
				$('.text-danger').text('手机号或验证码不能为空!');
				return false;
			}
		});
	})
</script>
`)
//line home\views\index\verify.qtpl:39
}

//line home\views\index\verify.qtpl:39
func (p *VerfyPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:39
	p.StreamRenderScript(qw422016)
	//line home\views\index\verify.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:39
}

//line home\views\index\verify.qtpl:39
func (p *VerfyPage) RenderScript() string {
	//line home\views\index\verify.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:39
	p.WriteRenderScript(qb422016)
	//line home\views\index\verify.qtpl:39
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:39
	return qs422016
//line home\views\index\verify.qtpl:39
}

//line home\views\index\verify.qtpl:41
func (p *VerfyPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:41
	qw422016.N().S(`
	`)
	//line home\views\index\verify.qtpl:43
	err := p.BPD.Data["error"]
	phone := p.BPD.Data["phone"]

	//line home\views\index\verify.qtpl:45
	qw422016.N().S(`
	
	`)
	//line home\views\index\verify.qtpl:47
	if err != nil {
		//line home\views\index\verify.qtpl:47
		qw422016.N().S(`
	 <div class="text-danger">`)
		//line home\views\index\verify.qtpl:48
		qw422016.E().S(err.(string))
		//line home\views\index\verify.qtpl:48
		qw422016.N().S(`</div>
	`)
		//line home\views\index\verify.qtpl:49
	}
	//line home\views\index\verify.qtpl:49
	qw422016.N().S(`
	
	<div class="text-center">
		<form class="form-horizontal" action="`)
	//line home\views\index\verify.qtpl:52
	qw422016.E().S(area.Url(p.BasePage, "verify", nil))
	//line home\views\index\verify.qtpl:52
	qw422016.N().S(`" method="POST">
			<div class="form-group">
				<label class="control-label col-md-2">手机号:</label>
				<div class="col-md-8">
					<input class="form-control" id="phone" name="phone" `)
	//line home\views\index\verify.qtpl:56
	if phone != nil {
		//line home\views\index\verify.qtpl:56
		qw422016.N().S(`value="`)
		//line home\views\index\verify.qtpl:56
		qw422016.E().S(phone.(string))
		//line home\views\index\verify.qtpl:56
		qw422016.N().S(`"`)
		//line home\views\index\verify.qtpl:56
	}
	//line home\views\index\verify.qtpl:56
	qw422016.N().S(` />
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-md-2">验证码:</label>
				<div class="col-md-8">
					<input class="form-control" id="vc" name="vcode" />
				</div>
				<div class="col-md-2">
					<img id="vcode" src="`)
	//line home\views\index\verify.qtpl:65
	qw422016.N().S(commonhtmlhelper.GenerateVerifyImgLink("/api/verifyimg", "vcode"))
	//line home\views\index\verify.qtpl:65
	qw422016.N().S(`" title="点击切换验证码" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<button type="submit" class="btn btn-default">去逛逛</button>
				</div>
			</div>
		</form>
	</div>
`)
//line home\views\index\verify.qtpl:75
}

//line home\views\index\verify.qtpl:75
func (p *VerfyPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:75
	p.StreamRenderBody(qw422016)
	//line home\views\index\verify.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:75
}

//line home\views\index\verify.qtpl:75
func (p *VerfyPage) RenderBody() string {
	//line home\views\index\verify.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:75
	p.WriteRenderBody(qb422016)
	//line home\views\index\verify.qtpl:75
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:75
	return qs422016
//line home\views\index\verify.qtpl:75
}
