// This file is automatically generated by qtc from "verify.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home\views\index\verify.qtpl:1
package index

//line home\views\index\verify.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Implements BasePage methods.
//

//line home\views\index\verify.qtpl:3
import "fasthttpweb/area"

//line home\views\index\verify.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home\views\index\verify.qtpl:6
type VerfyPage struct {
	*area.BasePage
}

//line home\views\index\verify.qtpl:11
func (p *VerfyPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
//line home\views\index\verify.qtpl:11
p.StreamRender_Title(qw422016) }

//line home\views\index\verify.qtpl:11
//line home\views\index\verify.qtpl:11
func (p *VerfyPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:11
	p.StreamRenderTitle(qw422016)
	//line home\views\index\verify.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:11
}

//line home\views\index\verify.qtpl:11
func (p *VerfyPage) RenderTitle() string {
	//line home\views\index\verify.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:11
	p.WriteRenderTitle(qb422016)
	//line home\views\index\verify.qtpl:11
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:11
	return qs422016
//line home\views\index\verify.qtpl:11
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:12
	qw422016.N().S(` `)
	//line home\views\index\verify.qtpl:12
	p.StreamRender_Kwd(qw422016)
	//line home\views\index\verify.qtpl:12
	qw422016.N().S(` `)
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:12
	p.StreamRenderKwd(qw422016)
	//line home\views\index\verify.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:12
func (p *VerfyPage) RenderKwd() string {
	//line home\views\index\verify.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:12
	p.WriteRenderKwd(qb422016)
	//line home\views\index\verify.qtpl:12
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:12
	return qs422016
//line home\views\index\verify.qtpl:12
}

//line home\views\index\verify.qtpl:14
func (p *VerfyPage) StreamRenderCss(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:14
	qw422016.N().S(`
	<style type="text/css">
		#vcode{
			cursor:pointer;
		}
	</style>
`)
//line home\views\index\verify.qtpl:20
}

//line home\views\index\verify.qtpl:20
func (p *VerfyPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:20
	p.StreamRenderCss(qw422016)
	//line home\views\index\verify.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:20
}

//line home\views\index\verify.qtpl:20
func (p *VerfyPage) RenderCss() string {
	//line home\views\index\verify.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:20
	p.WriteRenderCss(qb422016)
	//line home\views\index\verify.qtpl:20
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:20
	return qs422016
//line home\views\index\verify.qtpl:20
}

//line home\views\index\verify.qtpl:22
func (p *VerfyPage) StreamRenderScript(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:22
	qw422016.N().S(`
<script type="text/javascript">
	$(function(){
		$('#vcode').click(function(){
			$(this).prop('src','/api/verifyimg?r='+Math.random());
		});
		$(':submit').click(function(){
			var phone=$('#phone').val(),vcode=$('#vc').val();
			if(!(phone.length>0 && vcode.length>0)){
				$('.text-danger').text('手机号或验证码不能为空!');
				return false;
			}
		});
	})
</script>
`)
//line home\views\index\verify.qtpl:37
}

//line home\views\index\verify.qtpl:37
func (p *VerfyPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:37
	p.StreamRenderScript(qw422016)
	//line home\views\index\verify.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:37
}

//line home\views\index\verify.qtpl:37
func (p *VerfyPage) RenderScript() string {
	//line home\views\index\verify.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:37
	p.WriteRenderScript(qb422016)
	//line home\views\index\verify.qtpl:37
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:37
	return qs422016
//line home\views\index\verify.qtpl:37
}

//line home\views\index\verify.qtpl:39
func (p *VerfyPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line home\views\index\verify.qtpl:39
	qw422016.N().S(`
<div class="text-danger">
`)
	//line home\views\index\verify.qtpl:41
	if p.BPD.Data["ErrMsg"] != nil {
		//line home\views\index\verify.qtpl:41
		qw422016.N().S(`
`)
		//line home\views\index\verify.qtpl:42
		qw422016.E().S((p.BPD.Data["ErrMsg"]).(string))
		//line home\views\index\verify.qtpl:42
		qw422016.N().S(`
`)
		//line home\views\index\verify.qtpl:43
	}
	//line home\views\index\verify.qtpl:43
	qw422016.N().S(`
</div>
	<div class="text-center">
		<form action="/home/index/verify" method="POST">
			手机号:<input type="phone" id="phone" name="phone" value="`)
	//line home\views\index\verify.qtpl:47
	if p.BPD.Data["phone"] != nil {
		//line home\views\index\verify.qtpl:47
		qw422016.E().S(p.BPD.Data["phone"].(string))
		//line home\views\index\verify.qtpl:47
	}
	//line home\views\index\verify.qtpl:47
	qw422016.N().S(`" /><br />
			验证码:<input type="text" id="vc" name="vcode" /><img id="vcode" src="/api/verifyimg" title="点击切换验证码" />
			<button type="submit" class="btn btn-default">去逛逛</button>
		</form>
	</div>
`)
//line home\views\index\verify.qtpl:52
}

//line home\views\index\verify.qtpl:52
func (p *VerfyPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line home\views\index\verify.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home\views\index\verify.qtpl:52
	p.StreamRenderBody(qw422016)
	//line home\views\index\verify.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line home\views\index\verify.qtpl:52
}

//line home\views\index\verify.qtpl:52
func (p *VerfyPage) RenderBody() string {
	//line home\views\index\verify.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
	//line home\views\index\verify.qtpl:52
	p.WriteRenderBody(qb422016)
	//line home\views\index\verify.qtpl:52
	qs422016 := string(qb422016.B)
	//line home\views\index\verify.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
	//line home\views\index\verify.qtpl:52
	return qs422016
//line home\views\index\verify.qtpl:52
}
