// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\article\index.qtpl:1
package article

//line admin\views\article\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line admin\views\article\index.qtpl:4
import (
	"fasthttpweb/area"
)

//line admin\views\article\index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\article\index.qtpl:10
type IndexPage struct {
	*area.BasePage
}

//line admin\views\article\index.qtpl:15
func (p *IndexPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\article\index.qtpl:15
	p.StreamRender_Title(qw422016)
	//line admin\views\article\index.qtpl:15
	qw422016.N().S(` `)
//line admin\views\article\index.qtpl:15
}

//line admin\views\article\index.qtpl:15
func (p *IndexPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\article\index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\article\index.qtpl:15
	p.StreamRenderTitle(qw422016)
	//line admin\views\article\index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line admin\views\article\index.qtpl:15
}

//line admin\views\article\index.qtpl:15
func (p *IndexPage) RenderTitle() string {
	//line admin\views\article\index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\article\index.qtpl:15
	p.WriteRenderTitle(qb422016)
	//line admin\views\article\index.qtpl:15
	qs422016 := string(qb422016.B)
	//line admin\views\article\index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\article\index.qtpl:15
	return qs422016
//line admin\views\article\index.qtpl:15
}

//line admin\views\article\index.qtpl:16
func (p *IndexPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\article\index.qtpl:16
	p.StreamRender_Kwd(qw422016)
	//line admin\views\article\index.qtpl:16
	qw422016.N().S(` `)
//line admin\views\article\index.qtpl:16
}

//line admin\views\article\index.qtpl:16
func (p *IndexPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\article\index.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\article\index.qtpl:16
	p.StreamRenderKwd(qw422016)
	//line admin\views\article\index.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line admin\views\article\index.qtpl:16
}

//line admin\views\article\index.qtpl:16
func (p *IndexPage) RenderKwd() string {
	//line admin\views\article\index.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\article\index.qtpl:16
	p.WriteRenderKwd(qb422016)
	//line admin\views\article\index.qtpl:16
	qs422016 := string(qb422016.B)
	//line admin\views\article\index.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\article\index.qtpl:16
	return qs422016
//line admin\views\article\index.qtpl:16
}

//line admin\views\article\index.qtpl:18
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\article\index.qtpl:18
}

//line admin\views\article\index.qtpl:18
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\article\index.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\article\index.qtpl:18
	p.StreamRenderCss(qw422016)
	//line admin\views\article\index.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line admin\views\article\index.qtpl:18
}

//line admin\views\article\index.qtpl:18
func (p *IndexPage) RenderCss() string {
	//line admin\views\article\index.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\article\index.qtpl:18
	p.WriteRenderCss(qb422016)
	//line admin\views\article\index.qtpl:18
	qs422016 := string(qb422016.B)
	//line admin\views\article\index.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\article\index.qtpl:18
	return qs422016
//line admin\views\article\index.qtpl:18
}

//line admin\views\article\index.qtpl:20
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
	//line admin\views\article\index.qtpl:20
	qw422016.N().S(`
<script type="text/javascript" src="/public/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/public/ueditor/ueditor.all.js"></script>
<script type="text/javascript">
	$(function(){
		var editor = new baidu.editor.ui.Editor({initialFrameWidth: 784,initialFrameHeight: 400});
    	editor.render('ueditor');
	});
</script>
`)
//line admin\views\article\index.qtpl:29
}

//line admin\views\article\index.qtpl:29
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\article\index.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\article\index.qtpl:29
	p.StreamRenderScript(qw422016)
	//line admin\views\article\index.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line admin\views\article\index.qtpl:29
}

//line admin\views\article\index.qtpl:29
func (p *IndexPage) RenderScript() string {
	//line admin\views\article\index.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\article\index.qtpl:29
	p.WriteRenderScript(qb422016)
	//line admin\views\article\index.qtpl:29
	qs422016 := string(qb422016.B)
	//line admin\views\article\index.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\article\index.qtpl:29
	return qs422016
//line admin\views\article\index.qtpl:29
}

//line admin\views\article\index.qtpl:32
func (p *IndexPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\article\index.qtpl:32
	qw422016.N().S(`
	<div class="text-center">
		article- success
		<form action="/admin/article/create" method="POST">
			<textarea name="ueditor" id="ueditor"></textarea>
			<input type="submit" />
		</form>
	</div>
`)
//line admin\views\article\index.qtpl:40
}

//line admin\views\article\index.qtpl:40
func (p *IndexPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\article\index.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\article\index.qtpl:40
	p.StreamRenderBody(qw422016)
	//line admin\views\article\index.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line admin\views\article\index.qtpl:40
}

//line admin\views\article\index.qtpl:40
func (p *IndexPage) RenderBody() string {
	//line admin\views\article\index.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\article\index.qtpl:40
	p.WriteRenderBody(qb422016)
	//line admin\views\article\index.qtpl:40
	qs422016 := string(qb422016.B)
	//line admin\views\article\index.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\article\index.qtpl:40
	return qs422016
//line admin\views\article\index.qtpl:40
}
