// This file is automatically generated by qtc from "create.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\articletype\create.qtpl:1
package articletype

//line admin\views\articletype\create.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line admin\views\articletype\create.qtpl:2
import (
	"fasthttpweb/area"
)

//line admin\views\articletype\create.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\articletype\create.qtpl:8
type CreatePage struct {
	*area.BasePage
}

//line admin\views\articletype\create.qtpl:13
func (p *CreatePage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\create.qtpl:13
	p.BasePage.StreamRenderTitle(qw422016)
	//line admin\views\articletype\create.qtpl:13
	qw422016.N().S(` `)
//line admin\views\articletype\create.qtpl:13
}

//line admin\views\articletype\create.qtpl:13
func (p *CreatePage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\create.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\create.qtpl:13
	p.StreamRenderTitle(qw422016)
	//line admin\views\articletype\create.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\create.qtpl:13
}

//line admin\views\articletype\create.qtpl:13
func (p *CreatePage) RenderTitle() string {
	//line admin\views\articletype\create.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\create.qtpl:13
	p.WriteRenderTitle(qb422016)
	//line admin\views\articletype\create.qtpl:13
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\create.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\create.qtpl:13
	return qs422016
//line admin\views\articletype\create.qtpl:13
}

//line admin\views\articletype\create.qtpl:14
func (p *CreatePage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\create.qtpl:14
	p.BasePage.StreamRenderKwd(qw422016)
	//line admin\views\articletype\create.qtpl:14
	qw422016.N().S(` `)
//line admin\views\articletype\create.qtpl:14
}

//line admin\views\articletype\create.qtpl:14
func (p *CreatePage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\create.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\create.qtpl:14
	p.StreamRenderKwd(qw422016)
	//line admin\views\articletype\create.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\create.qtpl:14
}

//line admin\views\articletype\create.qtpl:14
func (p *CreatePage) RenderKwd() string {
	//line admin\views\articletype\create.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\create.qtpl:14
	p.WriteRenderKwd(qb422016)
	//line admin\views\articletype\create.qtpl:14
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\create.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\create.qtpl:14
	return qs422016
//line admin\views\articletype\create.qtpl:14
}

//line admin\views\articletype\create.qtpl:16
func (p *CreatePage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\articletype\create.qtpl:16
}

//line admin\views\articletype\create.qtpl:16
func (p *CreatePage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\create.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\create.qtpl:16
	p.StreamRenderCss(qw422016)
	//line admin\views\articletype\create.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\create.qtpl:16
}

//line admin\views\articletype\create.qtpl:16
func (p *CreatePage) RenderCss() string {
	//line admin\views\articletype\create.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\create.qtpl:16
	p.WriteRenderCss(qb422016)
	//line admin\views\articletype\create.qtpl:16
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\create.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\create.qtpl:16
	return qs422016
//line admin\views\articletype\create.qtpl:16
}

//line admin\views\articletype\create.qtpl:18
func (p *CreatePage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line admin\views\articletype\create.qtpl:18
}

//line admin\views\articletype\create.qtpl:18
func (p *CreatePage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\create.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\create.qtpl:18
	p.StreamRenderScript(qw422016)
	//line admin\views\articletype\create.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\create.qtpl:18
}

//line admin\views\articletype\create.qtpl:18
func (p *CreatePage) RenderScript() string {
	//line admin\views\articletype\create.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\create.qtpl:18
	p.WriteRenderScript(qb422016)
	//line admin\views\articletype\create.qtpl:18
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\create.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\create.qtpl:18
	return qs422016
//line admin\views\articletype\create.qtpl:18
}

//line admin\views\articletype\create.qtpl:20
func (p *CreatePage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\create.qtpl:20
	qw422016.N().S(`
	<div class="text-center">
		<form class="form-horizontal" action="`)
	//line admin\views\articletype\create.qtpl:22
	qw422016.E().S(area.Url(p.BasePage, "create", nil))
	//line admin\views\articletype\create.qtpl:22
	qw422016.N().S(`" method="POST">
			<div class="form-group">
				<label class="control-label col-md-2">名称：</label>
				<div class="col-md-10">
					<input class="form-control" id="Name" name="Name"  />
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-md-2">排序：</label>
				<div class="col-md-10">
					<input class="form-control" type="number" id="Ord" name="Ord"  />
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<button type="submit" class="btn btn-default">添加</button>
				</div>
			</div>
		</form>
	</div>
`)
//line admin\views\articletype\create.qtpl:42
}

//line admin\views\articletype\create.qtpl:42
func (p *CreatePage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\create.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\create.qtpl:42
	p.StreamRenderBody(qw422016)
	//line admin\views\articletype\create.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\create.qtpl:42
}

//line admin\views\articletype\create.qtpl:42
func (p *CreatePage) RenderBody() string {
	//line admin\views\articletype\create.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\create.qtpl:42
	p.WriteRenderBody(qb422016)
	//line admin\views\articletype\create.qtpl:42
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\create.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\create.qtpl:42
	return qs422016
//line admin\views\articletype\create.qtpl:42
}
