// This file is automatically generated by qtc from "detail.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\articletype\detail.qtpl:1
package articletype

//line admin\views\articletype\detail.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line admin\views\articletype\detail.qtpl:2
import (
	"fasthttpweb/area"
	"fasthttpweb/model"
)

//line admin\views\articletype\detail.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\articletype\detail.qtpl:9
type DetailPage struct {
	*area.BasePage
}

//line admin\views\articletype\detail.qtpl:14
func (p *DetailPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\detail.qtpl:14
	p.BasePage.StreamRenderTitle(qw422016)
	//line admin\views\articletype\detail.qtpl:14
	qw422016.N().S(` `)
//line admin\views\articletype\detail.qtpl:14
}

//line admin\views\articletype\detail.qtpl:14
func (p *DetailPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\detail.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\detail.qtpl:14
	p.StreamRenderTitle(qw422016)
	//line admin\views\articletype\detail.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\detail.qtpl:14
}

//line admin\views\articletype\detail.qtpl:14
func (p *DetailPage) RenderTitle() string {
	//line admin\views\articletype\detail.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\detail.qtpl:14
	p.WriteRenderTitle(qb422016)
	//line admin\views\articletype\detail.qtpl:14
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\detail.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\detail.qtpl:14
	return qs422016
//line admin\views\articletype\detail.qtpl:14
}

//line admin\views\articletype\detail.qtpl:15
func (p *DetailPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\detail.qtpl:15
	p.BasePage.StreamRenderKwd(qw422016)
	//line admin\views\articletype\detail.qtpl:15
	qw422016.N().S(` `)
//line admin\views\articletype\detail.qtpl:15
}

//line admin\views\articletype\detail.qtpl:15
func (p *DetailPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\detail.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\detail.qtpl:15
	p.StreamRenderKwd(qw422016)
	//line admin\views\articletype\detail.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\detail.qtpl:15
}

//line admin\views\articletype\detail.qtpl:15
func (p *DetailPage) RenderKwd() string {
	//line admin\views\articletype\detail.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\detail.qtpl:15
	p.WriteRenderKwd(qb422016)
	//line admin\views\articletype\detail.qtpl:15
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\detail.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\detail.qtpl:15
	return qs422016
//line admin\views\articletype\detail.qtpl:15
}

//line admin\views\articletype\detail.qtpl:17
func (p *DetailPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\articletype\detail.qtpl:17
}

//line admin\views\articletype\detail.qtpl:17
func (p *DetailPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\detail.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\detail.qtpl:17
	p.StreamRenderCss(qw422016)
	//line admin\views\articletype\detail.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\detail.qtpl:17
}

//line admin\views\articletype\detail.qtpl:17
func (p *DetailPage) RenderCss() string {
	//line admin\views\articletype\detail.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\detail.qtpl:17
	p.WriteRenderCss(qb422016)
	//line admin\views\articletype\detail.qtpl:17
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\detail.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\detail.qtpl:17
	return qs422016
//line admin\views\articletype\detail.qtpl:17
}

//line admin\views\articletype\detail.qtpl:19
func (p *DetailPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line admin\views\articletype\detail.qtpl:19
}

//line admin\views\articletype\detail.qtpl:19
func (p *DetailPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\detail.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\detail.qtpl:19
	p.StreamRenderScript(qw422016)
	//line admin\views\articletype\detail.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\detail.qtpl:19
}

//line admin\views\articletype\detail.qtpl:19
func (p *DetailPage) RenderScript() string {
	//line admin\views\articletype\detail.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\detail.qtpl:19
	p.WriteRenderScript(qb422016)
	//line admin\views\articletype\detail.qtpl:19
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\detail.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\detail.qtpl:19
	return qs422016
//line admin\views\articletype\detail.qtpl:19
}

//line admin\views\articletype\detail.qtpl:21
func (p *DetailPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\detail.qtpl:21
	qw422016.N().S(`
	<div class="text-center">
		`)
	//line admin\views\articletype\detail.qtpl:24
	art := p.BasePage.BPD.Data["Model"]
	var artVal *model.ArticleType
	if art != nil {
		artVal = art.(*model.ArticleType)
	}

	//line admin\views\articletype\detail.qtpl:29
	qw422016.N().S(`
		`)
	//line admin\views\articletype\detail.qtpl:30
	if artVal != nil {
		//line admin\views\articletype\detail.qtpl:30
		qw422016.N().S(`
			<div>
				名称:`)
		//line admin\views\articletype\detail.qtpl:32
		qw422016.E().S(artVal.Name)
		//line admin\views\articletype\detail.qtpl:32
		qw422016.N().S(`
			</div>
			<div>
				排序:`)
		//line admin\views\articletype\detail.qtpl:35
		qw422016.N().D(artVal.Ord)
		//line admin\views\articletype\detail.qtpl:35
		qw422016.N().S(`
			</div>
		`)
		//line admin\views\articletype\detail.qtpl:37
	}
	//line admin\views\articletype\detail.qtpl:37
	qw422016.N().S(`
	</div>
`)
//line admin\views\articletype\detail.qtpl:39
}

//line admin\views\articletype\detail.qtpl:39
func (p *DetailPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\detail.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\detail.qtpl:39
	p.StreamRenderBody(qw422016)
	//line admin\views\articletype\detail.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\detail.qtpl:39
}

//line admin\views\articletype\detail.qtpl:39
func (p *DetailPage) RenderBody() string {
	//line admin\views\articletype\detail.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\detail.qtpl:39
	p.WriteRenderBody(qb422016)
	//line admin\views\articletype\detail.qtpl:39
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\detail.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\detail.qtpl:39
	return qs422016
//line admin\views\articletype\detail.qtpl:39
}
