// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\views\articletype\index.qtpl:1
package articletype

//line admin\views\articletype\index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line admin\views\articletype\index.qtpl:4
import (
	"fasthttpweb/area"
	"fasthttpweb/model"
)

//line admin\views\articletype\index.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\views\articletype\index.qtpl:11
type IndexPage struct {
	*area.BasePage
}

//line admin\views\articletype\index.qtpl:16
func (p *IndexPage) StreamRenderTitle(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\index.qtpl:16
	p.BasePage.StreamRenderTitle(qw422016)
	//line admin\views\articletype\index.qtpl:16
	qw422016.N().S(` `)
//line admin\views\articletype\index.qtpl:16
}

//line admin\views\articletype\index.qtpl:16
func (p *IndexPage) WriteRenderTitle(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\index.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\index.qtpl:16
	p.StreamRenderTitle(qw422016)
	//line admin\views\articletype\index.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\index.qtpl:16
}

//line admin\views\articletype\index.qtpl:16
func (p *IndexPage) RenderTitle() string {
	//line admin\views\articletype\index.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\index.qtpl:16
	p.WriteRenderTitle(qb422016)
	//line admin\views\articletype\index.qtpl:16
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\index.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\index.qtpl:16
	return qs422016
//line admin\views\articletype\index.qtpl:16
}

//line admin\views\articletype\index.qtpl:17
func (p *IndexPage) StreamRenderKwd(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\index.qtpl:17
	p.BasePage.StreamRenderKwd(qw422016)
	//line admin\views\articletype\index.qtpl:17
	qw422016.N().S(` `)
//line admin\views\articletype\index.qtpl:17
}

//line admin\views\articletype\index.qtpl:17
func (p *IndexPage) WriteRenderKwd(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\index.qtpl:17
	p.StreamRenderKwd(qw422016)
	//line admin\views\articletype\index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\index.qtpl:17
}

//line admin\views\articletype\index.qtpl:17
func (p *IndexPage) RenderKwd() string {
	//line admin\views\articletype\index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\index.qtpl:17
	p.WriteRenderKwd(qb422016)
	//line admin\views\articletype\index.qtpl:17
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\index.qtpl:17
	return qs422016
//line admin\views\articletype\index.qtpl:17
}

//line admin\views\articletype\index.qtpl:19
func (p *IndexPage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line admin\views\articletype\index.qtpl:19
}

//line admin\views\articletype\index.qtpl:19
func (p *IndexPage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\index.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\index.qtpl:19
	p.StreamRenderCss(qw422016)
	//line admin\views\articletype\index.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\index.qtpl:19
}

//line admin\views\articletype\index.qtpl:19
func (p *IndexPage) RenderCss() string {
	//line admin\views\articletype\index.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\index.qtpl:19
	p.WriteRenderCss(qb422016)
	//line admin\views\articletype\index.qtpl:19
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\index.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\index.qtpl:19
	return qs422016
//line admin\views\articletype\index.qtpl:19
}

//line admin\views\articletype\index.qtpl:21
func (p *IndexPage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line admin\views\articletype\index.qtpl:21
}

//line admin\views\articletype\index.qtpl:21
func (p *IndexPage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\index.qtpl:21
	p.StreamRenderScript(qw422016)
	//line admin\views\articletype\index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\index.qtpl:21
}

//line admin\views\articletype\index.qtpl:21
func (p *IndexPage) RenderScript() string {
	//line admin\views\articletype\index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\index.qtpl:21
	p.WriteRenderScript(qb422016)
	//line admin\views\articletype\index.qtpl:21
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\index.qtpl:21
	return qs422016
//line admin\views\articletype\index.qtpl:21
}

//line admin\views\articletype\index.qtpl:23
func (p *IndexPage) StreamRenderBody(qw422016 *qt422016.Writer) {
	//line admin\views\articletype\index.qtpl:23
	qw422016.N().S(`
	`)
	//line admin\views\articletype\index.qtpl:25
	modelVal := p.BasePage.BPD.Data["Model"]
	var arts []model.ArticleType
	if modelVal != nil {
		arts = modelVal.([]model.ArticleType)
	}

	//line admin\views\articletype\index.qtpl:30
	qw422016.N().S(`
	<div class="text-center">
		<a class="btn btn-default" href="`)
	//line admin\views\articletype\index.qtpl:32
	qw422016.E().S(area.Url(p.BasePage, "create", nil))
	//line admin\views\articletype\index.qtpl:32
	qw422016.N().S(`">添加</a>
		
		`)
	//line admin\views\articletype\index.qtpl:34
	if arts != nil && len(arts) > 0 {
		//line admin\views\articletype\index.qtpl:34
		qw422016.N().S(`
		<table class="table table-bordered table-hover">
		`)
		//line admin\views\articletype\index.qtpl:36
		for _, v := range arts {
			//line admin\views\articletype\index.qtpl:36
			qw422016.N().S(`
		`)
			//line admin\views\articletype\index.qtpl:38
			id := int(v.ID)
			data := make(map[string]interface{})
			data["id"] = id

			//line admin\views\articletype\index.qtpl:41
			qw422016.N().S(`
			<tr>
				<td><a href="`)
			//line admin\views\articletype\index.qtpl:43
			qw422016.E().S(area.Url(p.BasePage, "detail", data))
			//line admin\views\articletype\index.qtpl:43
			qw422016.N().S(`">`)
			//line admin\views\articletype\index.qtpl:43
			qw422016.E().S(v.Name)
			//line admin\views\articletype\index.qtpl:43
			qw422016.N().S(`</a></td>
				<td>
					<a href="`)
			//line admin\views\articletype\index.qtpl:45
			qw422016.E().S(area.Url(p.BasePage, "edit", data))
			//line admin\views\articletype\index.qtpl:45
			qw422016.N().S(`">编辑</a>
					<a href="`)
			//line admin\views\articletype\index.qtpl:46
			qw422016.E().S(area.Url(p.BasePage, "mdelete", data))
			//line admin\views\articletype\index.qtpl:46
			qw422016.N().S(`">删除</a>
				</td>
			</tr>
		`)
			//line admin\views\articletype\index.qtpl:49
		}
		//line admin\views\articletype\index.qtpl:49
		qw422016.N().S(`
		</table>
		`)
		//line admin\views\articletype\index.qtpl:51
	}
	//line admin\views\articletype\index.qtpl:51
	qw422016.N().S(`
	</div>
`)
//line admin\views\articletype\index.qtpl:53
}

//line admin\views\articletype\index.qtpl:53
func (p *IndexPage) WriteRenderBody(qq422016 qtio422016.Writer) {
	//line admin\views\articletype\index.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\views\articletype\index.qtpl:53
	p.StreamRenderBody(qw422016)
	//line admin\views\articletype\index.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line admin\views\articletype\index.qtpl:53
}

//line admin\views\articletype\index.qtpl:53
func (p *IndexPage) RenderBody() string {
	//line admin\views\articletype\index.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\views\articletype\index.qtpl:53
	p.WriteRenderBody(qb422016)
	//line admin\views\articletype\index.qtpl:53
	qs422016 := string(qb422016.B)
	//line admin\views\articletype\index.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\views\articletype\index.qtpl:53
	return qs422016
//line admin\views\articletype\index.qtpl:53
}
