// This file is automatically generated by qtc from "baseView.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line baseView.qtpl:1
package area

//line baseView.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// This is a base page template. All the other template pages implement this interface.
//

//line baseView.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line baseView.qtpl:4
type Page interface {
	//line baseView.qtpl:4
	Title() string
	//line baseView.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
	//line baseView.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
	//line baseView.qtpl:4
	Kwd() string
	//line baseView.qtpl:4
	StreamKwd(qw422016 *qt422016.Writer)
	//line baseView.qtpl:4
	WriteKwd(qq422016 qtio422016.Writer)
	//line baseView.qtpl:4
	RenderBody() string
	//line baseView.qtpl:4
	StreamRenderBody(qw422016 *qt422016.Writer)
	//line baseView.qtpl:4
	WriteRenderBody(qq422016 qtio422016.Writer)
	//line baseView.qtpl:4
	RenderCss() string
	//line baseView.qtpl:4
	StreamRenderCss(qw422016 *qt422016.Writer)
	//line baseView.qtpl:4
	WriteRenderCss(qq422016 qtio422016.Writer)
	//line baseView.qtpl:4
	RenderScript() string
	//line baseView.qtpl:4
	StreamRenderScript(qw422016 *qt422016.Writer)
	//line baseView.qtpl:4
	WriteRenderScript(qq422016 qtio422016.Writer)
//line baseView.qtpl:4
}

// Page prints a page implementing Page interface.

//line baseView.qtpl:14
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line baseView.qtpl:14
	qw422016.N().S(`
<html>
	<head>
		<title>`)
	//line baseView.qtpl:17
	p.StreamTitle(qw422016)
	//line baseView.qtpl:17
	qw422016.N().S(`</title>
		<meta charset="utf-8" />
		<meta name="keywords" content="`)
	//line baseView.qtpl:19
	p.StreamKwd(qw422016)
	//line baseView.qtpl:19
	qw422016.N().S(`" />
		<link href="/public/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/public/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
		`)
	//line baseView.qtpl:22
	p.StreamRenderCss(qw422016)
	//line baseView.qtpl:22
	qw422016.N().S(`
	</head>
	<body>
		`)
	//line baseView.qtpl:25
	p.StreamRenderBody(qw422016)
	//line baseView.qtpl:25
	qw422016.N().S(`
		<script src="//cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
		<script src="/public/bootstrap/js/bootstrap.min.js"></script>
		`)
	//line baseView.qtpl:28
	p.StreamRenderScript(qw422016)
	//line baseView.qtpl:28
	qw422016.N().S(`
	</body>
</html>
`)
//line baseView.qtpl:31
}

//line baseView.qtpl:31
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line baseView.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line baseView.qtpl:31
	StreamPageTemplate(qw422016, p)
	//line baseView.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line baseView.qtpl:31
}

//line baseView.qtpl:31
func PageTemplate(p Page) string {
	//line baseView.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
	//line baseView.qtpl:31
	WritePageTemplate(qb422016, p)
	//line baseView.qtpl:31
	qs422016 := string(qb422016.B)
	//line baseView.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
	//line baseView.qtpl:31
	return qs422016
//line baseView.qtpl:31
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods
//

//line baseView.qtpl:36
type BasePageData struct {
	AreaName string
	CtrlName string
	Data     map[string]interface{}
}

//line baseView.qtpl:42
type BasePage struct{}

//line baseView.qtpl:44
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line baseView.qtpl:44
qw422016.N().S(`This is a base title`) }

//line baseView.qtpl:44
//line baseView.qtpl:44
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line baseView.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line baseView.qtpl:44
	p.StreamTitle(qw422016)
	//line baseView.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line baseView.qtpl:44
}

//line baseView.qtpl:44
func (p *BasePage) Title() string {
	//line baseView.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line baseView.qtpl:44
	p.WriteTitle(qb422016)
	//line baseView.qtpl:44
	qs422016 := string(qb422016.B)
	//line baseView.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line baseView.qtpl:44
	return qs422016
//line baseView.qtpl:44
}

//line baseView.qtpl:45
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line baseView.qtpl:45
qw422016.N().S(`This is a base body`) }

//line baseView.qtpl:45
//line baseView.qtpl:45
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	//line baseView.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line baseView.qtpl:45
	p.StreamBody(qw422016)
	//line baseView.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line baseView.qtpl:45
}

//line baseView.qtpl:45
func (p *BasePage) Body() string {
	//line baseView.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
	//line baseView.qtpl:45
	p.WriteBody(qb422016)
	//line baseView.qtpl:45
	qs422016 := string(qb422016.B)
	//line baseView.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
	//line baseView.qtpl:45
	return qs422016
//line baseView.qtpl:45
}

//line baseView.qtpl:46
func (p *BasePage) StreamRenderCss(qw422016 *qt422016.Writer) {
//line baseView.qtpl:46
qw422016.N().S(` `) }

//line baseView.qtpl:46
//line baseView.qtpl:46
func (p *BasePage) WriteRenderCss(qq422016 qtio422016.Writer) {
	//line baseView.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line baseView.qtpl:46
	p.StreamRenderCss(qw422016)
	//line baseView.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line baseView.qtpl:46
}

//line baseView.qtpl:46
func (p *BasePage) RenderCss() string {
	//line baseView.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
	//line baseView.qtpl:46
	p.WriteRenderCss(qb422016)
	//line baseView.qtpl:46
	qs422016 := string(qb422016.B)
	//line baseView.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
	//line baseView.qtpl:46
	return qs422016
//line baseView.qtpl:46
}

//line baseView.qtpl:47
func (p *BasePage) StreamRenderScript(qw422016 *qt422016.Writer) {
//line baseView.qtpl:47
qw422016.N().S(` `) }

//line baseView.qtpl:47
//line baseView.qtpl:47
func (p *BasePage) WriteRenderScript(qq422016 qtio422016.Writer) {
	//line baseView.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line baseView.qtpl:47
	p.StreamRenderScript(qw422016)
	//line baseView.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line baseView.qtpl:47
}

//line baseView.qtpl:47
func (p *BasePage) RenderScript() string {
	//line baseView.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
	//line baseView.qtpl:47
	p.WriteRenderScript(qb422016)
	//line baseView.qtpl:47
	qs422016 := string(qb422016.B)
	//line baseView.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
	//line baseView.qtpl:47
	return qs422016
//line baseView.qtpl:47
}
